five := 1 + 1

print(1)

for i in range(1, 2, 3) do
    print(i)
endfor

print(five, 4, 3, `two`)

obj := {
    a = 1,
    b = 2,
}

lambda := fn (arg1)
    print(arg1)
endfn

class : Test begin
endclass


lambda(3.14)
print(`a is `, obj.a)
try
    print(obj.c)
catch err : ReferenceError
    print(`Caught`)
endtry
print(arg1) "This should throw an error"
